version: '3.8'

services:
  # 1. Base de Datos MySQL
  mysqldb:
    image: mysql:8.0
    container_name: muebleria_db_container
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306" # Mapeamos al 3307 externo para no chocar con tu XAMPP local
    volumes:
      - db_data:/var/lib/mysql # Persistencia de datos

  # 2. Backend (Spring Boot)
  backend:
    build: ./backend # Busca el Dockerfile en la carpeta backend
    container_name: muebleria_backend_container
    depends_on:
      - mysqldb # Espera a que la BD inicie
    environment:
      # OJO AQUÍ: Dentro de Docker, el host NO es 'localhost', es el nombre del servicio 'mysqldb'
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:8080"

  # 3. Frontend (React + Nginx)
  frontend:
    build: ./frontend # Busca el Dockerfile en la carpeta frontend
    container_name: muebleria_frontend_container
    depends_on:
      - backend
    ports:
      - "80:80" # Podrás ver la web en http://localhost

volumes:
  db_data: